### ISSUE TITLE
Queue Issues

### ISSUE THREAD

**Issue by Reanmachine** [swimmadude66/YTRadio#31] opened 2015-10-22 19:42 UTC
If I'm in queue but not playing, and i change the top song of my playlist my next playing song does not update. Additionally when the other song finishes the top item of my queue gets pushed to the bottom.
1. Set up Playlist with songs A, B, C
2. Join the queue behind someone else playing
3. Note that song A is listed as your queued song
4. Move song B to the top

Expected:

Queued song changes to B, B is played, B moves to the bottom of the playlist when it is done.

Actual:

Queued song stays as A, A is played, B moves to the bottom of the playlist when it's done.

**Comment by localyost3000** [comment] 2015-10-23 12:45
Not a bug, but rather a different approach to queuing. There has been a hot debate on what the approach should be on Issue #20 

Closed as Duplicate of #20

**Closed as completed by localyost3000** 2015-10-23 12:45 UTC
