### ISSUE TITLE
Failure to skip item that has been "removed by user"

### ISSUE THREAD

**Issue by JefferysTuber** [swimmadude66/YTRadio#29] opened 2015-10-21 14:13 UTC
One of my tracks was "removed by the user", it appeared to be stuck with 0:00/0:00.

This is a weak bug report, as I did not have my head phones on at the time, don't know if it was client side only, don't know if any music was actually playing, and did not try to repeat the behavior before skipping the item and removing it from my playlist. I had intended to provide a link to the broken song, but well .... its been removed (duh).

Still, it seems worthy of reporting. I suppose could upload a video and test the behavior after it is removed.

**Comment by localyost3000** [comment] 2015-10-23 20:34
I think this is probably a duplicate of #10 but it is made worse by the new logic which checks playIDs. If a video cannot play, it gets no playID, and thus cannot be skipped.

**Closed as completed by localyost3000** 2015-10-23 20:34 UTC
